# Generated by Django 5.2.1 on 2025-06-06 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_hcp'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')])),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')])),
                ('hcp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.hcp')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
